version: 0.2

# https://medium.com/swlh/setup-a-continous-delivery-cd-pipeline-in-aws-for-a-net-core-3-x-web-api-ca34271bd4fc
# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-windows.html
env:
  variables:
    SOLUTION: .\TestDeployApp.sln
    DOTNET_FRAMEWORK: 7.0

phases:
  install:
    runtime-versions:
      dotnet: latest

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore

  build:
    commands:
      - echo Build started on `date`
      - dotnet build

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 --self-contained false

artifacts:
  files:
    - '**/*'
  base-directory: './TestDeployApp/bin/Release/net$env:DOTNET_FRAMEWORK/linux-x64/publish/'
  discard-paths: no